<?php



/**
 * Skeleton subclass for representing a row from the 'system_event_instance' table.
 *
 * 
 *
 * This class was autogenerated by Propel 1.5.3 on:
 *
 * Thu Jul 14 19:49:20 2011
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 *
 * @package    propel.generator.plugins.sfAltumoPlugin.lib.model
 */
class SystemEventInstance extends BaseSystemEventInstance {

} // SystemEventInstance
